# Generated by Django 3.2 on 2021-04-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'álbum', 'verbose_name_plural': 'álbuns'},
        ),
        migrations.AlterModelOptions(
            name='cancao',
            options={'verbose_name': 'canção', 'verbose_name_plural': 'canções'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'gênero', 'verbose_name_plural': 'gêneros'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobre', models.TextField()),
                ('data_fundacao', models.DateField(blank=True, null=True)),
                ('integrantes', models.ManyToManyField(to='api.Artista')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cancao',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grupo'),
        ),
    ]
