# Generated by Django 3.2 on 2021-04-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210429_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancao',
            name='artista_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.artista'),
        ),
    ]
