# Generated by Django 3.2 on 2021-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cancao_artista_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
