# Generated by Django 3.2 on 2021-04-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_faixa_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancao',
            name='letra',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
