# Generated by Django 3.2 on 2021-04-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cancao_letra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grupo'),
        ),
    ]
