# Generated by Django 3.2 on 2021-04-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_album_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='imagem',
            field=models.ImageField(default=1, upload_to='imagens/artistas/'),
            preserve_default=False,
        ),
    ]
