# Generated by Django 3.2 on 2021-04-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_artista_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/artistas/'),
        ),
    ]
